name: Build Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  assemble:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release APK
        run: ./gradlew :app:assembleRelease

      - name: Rename APK
        run: |
          cd app/build/outputs/apk/release
          mv app-release-unsigned.apk glyph-catch-${{ github.ref_name }}.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/glyph-catch-${{ github.ref_name }}.apk
          draft: false
          prerelease: false
